apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pletor

resources:
  - ../../base

patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml

replicas:
  - name: frontend
    count: 1
  - name: backend
    count: 1

images:
  - name: ghcr.io/pletor/pletor-frontend
    newName: pletor-frontend
    newTag: local
  - name: ghcr.io/pletor/pletor-backend
    newName: pletor-backend
    newTag: local
