"""add_tree_node_table

Revision ID: 7d4de70eeeee
Revises: 92944c6c1a3b
Create Date: 2026-03-28 14:31:37.522970
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d4de70eeeee'
down_revision: Union[str, None] = '92944c6c1a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree_node',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('canvas_id', sa.String(), nullable=False),
    sa.Column('lexical_order', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_collapsed', sa.Boolean(), nullable=False),
    sa.Column('is_mirror_of', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['is_mirror_of'], ['tree_node.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['tree_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tree_node_canvas', 'tree_node', ['canvas_id'], unique=False)
    op.create_index('ix_tree_node_parent_order', 'tree_node', ['parent_id', 'lexical_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tree_node_parent_order', table_name='tree_node')
    op.drop_index('ix_tree_node_canvas', table_name='tree_node')
    op.drop_table('tree_node')
    # ### end Alembic commands ###
