"""initial schema

Revision ID: 92944c6c1a3b
Revises: 
Create Date: 2026-03-27 19:22:04.693378
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92944c6c1a3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canvas_node',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('canvas_id', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('workflowy_node_id', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('constraints', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_canvas_node_canvas_id', 'canvas_node', ['canvas_id'], unique=False)
    op.create_table('agent_execution',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('canvas_node_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('output', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canvas_node_id'], ['canvas_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_execution_canvas_node_id', 'agent_execution', ['canvas_node_id'], unique=False)
    op.create_index('ix_agent_execution_status', 'agent_execution', ['status'], unique=False)
    op.create_table('canvas_edge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('canvas_id', sa.String(), nullable=False),
    sa.Column('edge_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('animated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['canvas_node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['canvas_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_canvas_edge_canvas_id', 'canvas_edge', ['canvas_id'], unique=False)
    op.create_index('ix_canvas_edge_source_id', 'canvas_edge', ['source_id'], unique=False)
    op.create_index('ix_canvas_edge_target_id', 'canvas_edge', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_canvas_edge_target_id', table_name='canvas_edge')
    op.drop_index('ix_canvas_edge_source_id', table_name='canvas_edge')
    op.drop_index('ix_canvas_edge_canvas_id', table_name='canvas_edge')
    op.drop_table('canvas_edge')
    op.drop_index('ix_agent_execution_status', table_name='agent_execution')
    op.drop_index('ix_agent_execution_canvas_node_id', table_name='agent_execution')
    op.drop_table('agent_execution')
    op.drop_index('ix_canvas_node_canvas_id', table_name='canvas_node')
    op.drop_table('canvas_node')
    op.drop_table('canvas')
    # ### end Alembic commands ###
