apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pletor

resources:
  - ../../base
  - hpa.yaml

patches:
  - path: configmap-patch.yaml

replicas:
  - name: frontend
    count: 2
  - name: backend
    count: 2

images:
  - name: ghcr.io/pletor/pletor-frontend
    newTag: latest
  - name: ghcr.io/pletor/pletor-backend
    newTag: latest
